### ISSUE TITLE
"make" fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by dcon691** [NCAR/lrose-solo3#1]
I am trying to install solo3 on Ubuntu 18.04, however the "make" command keeps failing. Attached is the output when running "sudo make".

These steps run fine.
  runAutoConf.py
./configure --prefix=/usr/local

Following the instructions here:
https://github.com/NCAR/lrose-solo3/blob/master/README.solo3.txt

Thank you for the help in advance!

[output.txt](https://github.com/NCAR/lrose-solo3/files/2087324/output.txt)
[output2.txt](https://github.com/NCAR/lrose-solo3/files/2087325/output2.txt)

**Comment by burghart** [comment]
I haven't tested under Ubuntu 18.04, but the same build issue came up with CentOS 7 and is fixed by commit 590fa3c.
